### ISSUE TITLE
Akave SDK CLI - Alpha Testnet

### ISSUE THREAD

**Issue by rikysya** [akave-ai/akavesdk#2]
![Primary_BLUE_2](https://github.com/user-attachments/assets/8903011e-1b20-404f-a557-b53aa4532c7d)

### Hello Fellows !
This Phase is about getting familiar with the Akave SDK CLI to interact with our hosted Akave Storage Nodes. Follow the guide below. Looking forward to the feedback and answers. Thank you!

## Requirement
* OS: Linux or macOS
* Read our [Documentation](https://github.com/akave-ai/akavesdk/blob/main/README.md)
* Your assigned POD url

🚀 This post if you are participating in this testing round. If you aren't able to join for some reason, please reach out to me @Angelo-gh3990 here or on Telegram!

## Task assignment
1. Install Go version Go 1.22+.
2. Clone `akavesdk` repo

SSH
```
git clone git@github.com:akave-ai/akavesdk.git
```
HTTPS
```
git clone https://github.com/akave-ai/akavesdk.git
```
3. Build SDK CLI
```
make build
```
This command will build CLI binary and put it into `bin` folder `$project/bin/akavecli` 
 
## Test Operations

Execute every command from README and post result here.

Random file generation
```
# generate random 100MB file
dd if=/dev/urandom of=temp_100MB_file bs=1M count=100 iflag=fullblock
```
```
# generate random 1GB file
dd if=/dev/urandom of=temp_1GB_file bs=1G count=1 iflag=fullblock
```

Example file upload
```bash
# From akavesdk repo root directory after binary is built
# create new bucket
./bin/akavecli bucket create example-bucket --node-address your-pod-address.akave.ai:5000

# generate random 100MB file
dd if=/dev/urandom of=temp_100MB_file bs=1M count=100 iflag=fullblock

# upload file to bucket
./bin/akavecli file upload example-bucket temp_100MB_file --node-address your-pod-address.akave.ai:5000

# download file from a bucket

# create a folder to put that file into
mkdir output

# download a file
./bin/akavecli file download example-bucket temp_100MB_file ./output --node-address your-pod-address.akave.ai:5000


# check that file contents match and downloaded file is not tampered
cmp temp_100MB_file ./output/temp_100MB_file
```

**Reply with when completed:**

* [ ]  - 🦭If you have successfully created, viewed and listed a bucket.
* [ ]  - 💻 If you have successfully uploaded, downloaded, listed and looked at the file info for a file size larger then 100+ MB.
* [ ]  - 💻 If you have successfully uploaded, downloaded, listed and looked at the file info for a file size larger then 5+ GB.

❗ Disclaimer; right now the size of the uploaded file is limited by the size of your local physical memory.

## UI Feedback and Alerting
* What would you like on the first overview page?
* What features or changes would you suggest to improve to the UI?
* Is there anything you felt was missing that should be included?
* What would you like to have alerts on, and where?

❗ Create [an issue](https://github.com/akave-ai/akavesdk/issues/new) if you think there is a bug, don't forget to attach the logs! 🐛

If you have any questions or need help:

* Reply in this issue below
